export const exportToCSV = (transactions, currency = '₹') => {
  if (!transactions || transactions.length === 0) {
    alert('No transactions to export.');
    return;
  }

  const headers = ['Date', 'Time', 'Friend', 'Type', `Amount (${currency})`, 'Impact on You', 'Category', 'Description / Note', 'Payment Method', 'Receipt Note'];
  
  const rows = transactions.map(t => [
    `"${t.date}"`,
    `"${t.time || ''}"`,
    `"${(t.friend?.name || '').replace(/"/g, '""')}"`,
    `"${t.type}"`,
    t.amount,
    t.impactOnUser,
    `"${t.category}"`,
    `"${(t.note || '').replace(/"/g, '""')}"`,
    `"${t.paymentMethod || ''}"`,
    `"${(t.receiptNote || '').replace(/"/g, '""')}"`
  ]);

  const csvContent = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(e => e.join(','))].join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `money_tracker_export_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const printFriendStatement = (friendLedger, currency = '₹') => {
  if (!friendLedger || !friendLedger.friend) return;
  const { friend, currentBalance, transactions } = friendLedger;

  const statusText = currentBalance > 0 
    ? `Friend Owes You: ${currency}${Math.abs(currentBalance).toLocaleString()}`
    : currentBalance < 0 
    ? `You Owe Friend: ${currency}${Math.abs(currentBalance).toLocaleString()}`
    : 'All Dues Settled (₹0)';

  const printWindow = window.open('', '_blank');
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Statement - ${friend.name}</title>
      <style>
        body { font-family: system-ui, -apple-system, sans-serif; padding: 2.5rem; color: #0f172a; max-width: 800px; margin: auto; }
        .header { border-bottom: 2px solid #6366f1; padding-bottom: 1rem; margin-bottom: 1.5rem; display: flex; justify-content: space-between; align-items: flex-end; }
        .title { font-size: 1.75rem; font-weight: 800; color: #1e1b4b; }
        .badge { display: inline-block; padding: 0.5rem 1rem; border-radius: 8px; font-weight: 700; font-size: 1.1rem; margin: 1rem 0; background: #e0e7ff; color: #3730a3; }
        table { width: 100%; border-collapse: collapse; margin-top: 1.25rem; font-size: 0.9rem; }
        th { background: #f1f5f9; text-align: left; padding: 0.75rem; border-bottom: 2px solid #cbd5e1; font-weight: 700; }
        td { padding: 0.75rem; border-bottom: 1px solid #e2e8f0; }
        .green { color: #059669; font-weight: bold; }
        .red { color: #dc2626; font-weight: bold; }
        .footer { margin-top: 2.5rem; font-size: 0.8rem; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 1rem; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="title">Friend Money Tracker</div>
          <div style="color: #64748b; font-size: 0.9rem; margin-top: 0.25rem;">Ledger Statement for <strong>${friend.name}</strong> (${friend.relationshipTag || 'Friend'})</div>
        </div>
        <div style="font-size: 0.85rem; color: #64748b;">${new Date().toLocaleDateString()}</div>
      </div>
      
      <div class="badge">${statusText}</div>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Category</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Running Balance</th>
          </tr>
        </thead>
        <tbody>
          ${transactions.map(t => `
            <tr>
              <td>${t.date} ${t.time || ''}</td>
              <td>${t.note}</td>
              <td>${t.category}</td>
              <td>${t.type}</td>
              <td class="${t.impactOnUser > 0 ? 'green' : t.impactOnUser < 0 ? 'red' : ''}">
                ${t.impactOnUser > 0 ? '+' : t.impactOnUser < 0 ? '-' : ''}${currency}${t.amount.toLocaleString()}
              </td>
              <td><strong>${currency}${t.runningBalance.toLocaleString()}</strong></td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        Generated by Friend Money Tracker • All records accurate & verified.
      </div>
    </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 500);
};
